ip: "[0-9]{1,3}(\\.[0-9]{1,3}){3}"
quote: "[^\"]*"
url: "(-|(?:http(s)?:\\/\\/)?[\\w.-]+(?:\\.[\\w\\.-]+)+[\\w\\-\\._~:/?#[\\]@!\\$&\'\\(\\)\\*\\+,;=.]+)"
int: "[0-9]+"
double: "[0-9]+|[0-9]+\\.[0-9]+"
